steps:
  - name: 'python:3.7-slim'
    id: Unit Tests
    entrypoint: /bin/sh
    args:
    - -c
    - 'pip install -r requirements.txt && pip install -r tests/requirements.txt && python -m pytest -W ignore::DeprecationWarning -v'
